language: ruby
cache: bundler
rvm:
- 2.2
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: gh-pages
  email: kasper@friischristensen.com
  on:
    branch: master
