# Jekyll config file for static variables

# Site settings
title: Fyntech - Tech Events på Fyntech
description: En samling af spændende og interessante Tech relaterede events på Fyn.
baseurl: ""
github_username: https://github.com/fyntech
url: http://fyntech.dk/

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
#minima
gems:
#  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
